version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
#    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  book-flight-module-chrome:
    image: pneel141/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight.xml
    volumes:
      - ./output/flight-result-chrome:/usr/share/udemy/test-output

  book-flight-module_firfox:
    image: pneel141/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=book-flight.xml
    volumes:
      - ./output/flight-result-firefox:/usr/share/udemy/test-output

